[[JuliaNoGPL]]
arch = "x86_64"
git-tree-sha1 = "37c172680f4eeaa0b52f96dfeb4cea3a5979124f"
libc = "glibc"
os = "linux"

    [[JuliaNoGPL.download]]
    sha256 = "c9f12e81124b73a37258ada7899e5a73846e6e10747f6d6b85200f65e7ee3ab0"
    url = "https://github.com/gbaraldi/a_julia_artifact/releases/download/julia-1.12-nogpl-1/julia-cdaa753cd7-linux-x86_64-stripped.tar.gz"
[[JuliaNoGPL]]
arch = "aarch64"
git-tree-sha1 = "a8251653e9467eb320f4a58c592ef49e6b0ead6e"
os = "macos"

    [[JuliaNoGPL.download]]
    sha256 = "982f6f71a6633a314aa27fa58f77661109fbfc28555067761251306e1e23801d"
    url = "https://github.com/gbaraldi/a_julia_artifact/releases/download/julia-1.12-nogpl-1/julia-cdaa753cd7-macos-aarch64-stripped.tar.gz"
[[JuliaNoGPL]]
arch = "x86_64"
git-tree-sha1 = "f43a14cad27ffa703fc74ff937bc69440be791e9"
os = "windows"

    [[JuliaNoGPL.download]]
    sha256 = "a124f03af4fef4b56a49d73ae61db958d97c8665d2e8e9b07776bf6a88bef19a"
    url = "https://github.com/gbaraldi/a_julia_artifact/releases/download/julia-1.12-nogpl-1/julia-cdaa753cd7-windows-x86_64-stripped.tar.gz"
