[[JuliaNoGPL]]
arch = "x86_64"
git-tree-sha1 = "f5381231b1a5a2ccc1f85f4aa44e82e415bc611e"
libc = "glibc"
os = "linux"

    [[JuliaNoGPL.download]]
    sha256 = "fd40f73eaa494589e63f7df1797cb534d4c21b5a79784301557189b25c5eee0b"
    url = "https://github.com/gbaraldi/a_julia_artifact/releases/download/julia-1.12-nogpl-1/julia-cdaa753cd7-linux-x86_64-stripped.tar.gz"
[[JuliaNoGPL]]
arch = "aarch64"
git-tree-sha1 = "a35e4c6eb61e6544a96787e29cdac0bd7429d2c6"
os = "macos"

    [[JuliaNoGPL.download]]
    sha256 = "9b820779346731ba5bef32448df27fcf61b092e931b0195b8b5f62e1301e97ab"
    url = "https://github.com/gbaraldi/a_julia_artifact/releases/download/julia-1.12-nogpl-1/julia-cdaa753cd7-macos-aarch64-stripped.tar.gz"
[[JuliaNoGPL]]
arch = "x86_64"
git-tree-sha1 = "44e636f7e5a7da9db423ff5332dcbea57775e77b"
os = "windows"

    [[JuliaNoGPL.download]]
    sha256 = "8b243521ba036851eec8036a7bce758a3af44dc0d21a31feeac61efc18f50cde"
    url = "https://github.com/gbaraldi/a_julia_artifact/releases/download/julia-1.12-nogpl-1/julia-cdaa753cd7-windows-x86_64-stripped.tar.gz"
